[2020-12-26 20:34:33,552] ERROR in app: Exception on /erina/alive [GET]
Traceback (most recent call last):
  File "/Users/animenosekai/miniforge3/lib/python3.9/site-packages/flask_sockets.py", line 40, in __call__
    handler, values = adapter.match()
  File "/Users/animenosekai/miniforge3/lib/python3.9/site-packages/werkzeug/routing.py", line 1945, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/animenosekai/miniforge3/lib/python3.9/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/animenosekai/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/animenosekai/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/animenosekai/miniforge3/lib/python3.9/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/animenosekai/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/animenosekai/miniforge3/lib/python3.9/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/animenosekai/Documents/Coding/Projects/Project_Erina/ErinaServer/Server.py", line 72, in decorated
    return function(*args, **kwargs)
  File "/Users/animenosekai/Documents/Coding/Projects/Project_Erina/ErinaServer/Erina/admin/Config.py", line 480, in alive
    return makeResponse({"message": "Yes, I'm alive!", "success": True}, 200, request.args)
  File "/Users/animenosekai/Documents/Coding/Projects/Project_Erina/ErinaServer/Erina/admin/Config.py", line 41, in makeResponse
    if not token_verification.success:
AttributeError: 'dict' object has no attribute 'success'
[Erina] Initializing ErinaServer
[Erina] Initializing Erina configuration...
[Erina] ---> Initializing Static File Endpoints
[Erina] ---> Initializing API
[Erina] ---> Initializing ErinaAdmin
[Erina] ---> Initializing Custom Endpoints
[Erina] ---> Initializing ErinaConsole
[Erina] Running ErinaServer...
[Erina] Starting to check for timeouts and updates...
[Erina] Goodbye!
